name: DistShiftEnv
module: minigrid.envs.distshift
class: DistShiftEnv
class_params:
  width: 9
  height: 7
  render_mode: rgb_array

actions: [forward, left, right]
probabilities:
  forward: [0.8, 0.1, 0.1]
  left: [0.1, 0.8, 0.1]
  right: [0.1, 0.1, 0.8]