name: FourRoomsEnv
module: minigrid.envs.fourrooms
class: FourRoomsEnv
class_params:
  render_mode: rgb_array
  max_steps: 2000
actions: [forward, left, right]
probabilities:
  forward: [0.99, 0.005, 0.005]
  left: [0.005, 0.99, 0.005]
  right: [0.005, 0.005, 0.99]
