name: MultiRoomEnv
module: minigrid.envs.multiroom
class: MultiRoomEnv
class_params:
  render_mode: rgb_array
  maxRoomSize: 8
  minNumRooms: 3
  maxNumRooms: 3
actions: [forward, left, right, toggle]
probabilities:
  forward: [0.7, 0.1, 0.1, 0.1]
  left: [0.1, 0.7, 0.1, 0.1]
  right: [0.1, 0.1, 0.7, 0.1]
  toggle: [0.1, 0.1, 0.1, 0.7]