name: DoorKeyEnv
module: minigrid.envs.doorkey
class: DoorKeyEnv
class_params:
  size: 8
  render_mode: rgb_array
actions: [forward, left, right, pickup, toggle]
probabilities:
  forward: [0.6, 0.1, 0.1, 0.1, 0.1]
  left: [0.1, 0.6, 0.1, 0.1, 0.1]
  right: [0.1, 0.1, 0.6, 0.1, 0.1]
  pickup: [0.1, 0.1, 0.1, 0.6, 0.1]
  toggle: [0.1, 0.1, 0.1, 0.1, 0.6]