name: GoToObjectEnv
module: minigrid.envs.gotoobject
class: GoToObjectEnv
class_params:
  render_mode: rgb_array
  max_steps: 500
actions: [forward, left, right, done]
probabilities:
  forward: [0.7, 0.1, 0.1, 0.1]
  left: [0.1, 0.7, 0.1, 0.1]
  right: [0.1, 0.1, 0.7, 0.1]
  done: [0.1, 0.1, 0.1, 0.7]